extends: [[spectral:oas, all]]

functionsDir: ./src/spectral/

functions: 
  - ensureSimpleDescription
  - validateOperationIdFormat
  - ensurePropertiesExample
  - ensureAllOfOrder
  - ensureLocalReferencesInAllOf
  - ensureAllArraysHaveItemTypes

rules:
  tag-description: false
  openapi-tags-alphabetical: false
  example-value-or-externalValue: false
  operation-summary-formatted: false
  oas3-unused-components-schema: false

  ensure-endpoint-summary:
    description: Endpoints must have a summary.
    given: $.paths[*][*]
    severity: error
    recommended: true
    message: "{{error}}"
    then:
      field: summary
      function: truthy

  ensure-resource-description:
    description: Resources must have a description.
    given: $.components.schemas[*]
    severity: error
    recommended: true
    message: "{{error}}"
    then:
      field: description
      function: truthy
  
  ensure-param-description:
    description: Parameters must have a description.
    given: $..*.parameters[*]
    severity: error
    recommended: true
    message: "{{error}}"
    then:
      field: description
      function: truthy
    
  ensure-properties-description:
    description: Properties must have a description.
    given: $..*.properties[*]
    severity: error
    recommended: true
    resolved: true
    message: "{{error}}"
    then:
      function: ensureSimpleDescription
  
  ensure-operation-id-format:
    description: An operation ID must follow our required format
    given: $.paths[*][*]
    severity: error
    recommended: true
    resolved: true
    message: "{{error}}"
    then:
      function: validateOperationIdFormat
  
  ensure-param-examples:
    description: Parameters must have examples.
    given: $..*.parameters[*]
    severity: error
    recommended: true
    message: "{{error}}"
    then:
      field: example
      function: truthy

  ensure-properties-example:
    description: Properties must have examples.
    given: $..*.properties[*]
    severity: error
    recommended: true
    resolved: true
    message: "{{error}}"
    then:
      function: ensurePropertiesExample

  ensure-additional-properties-example:
    description: Additional properties must have examples.
    given: $..*.additionalProperties
    severity: error
    recommended: true
    resolved: true
    message: "{{error}}"
    then:
      function: ensurePropertiesExample

  ensure-allof-order:
    description: Ensures order of items in an allOf
    given: '$..*.allOf'
    severity: error
    recommended: true
    resolved: false
    message: "{{error}}"
    then:
      function: ensureAllOfOrder

  ensure-local-references-in-allof: 
    description: Ensures order of items in an allOf for properties
    given: '$.paths..*.properties..*'
    severity: error
    recommended: true
    resolved: false
    message: "{{error}}"
    then:
      function: ensureLocalReferencesInAllOf

  ensure-array-properties-have-items-with-type: 
    description: Ensures all array properties have an items attribute with a type
    given: '$..*.properties[*]'
    severity: error
    recommended: true
    resolved: false
    message: "{{error}}"
    then:
      function: ensureAllArraysHaveItemTypes

  ensure-array-params-have-items-with-type: 
    description: Ensures all array parameters have an items attribute with a type
    given: '$..*.parameters[*]'
    severity: error
    recommended: true
    resolved: false
    message: "{{error}}"
    then:
      function: ensureAllArraysHaveItemTypes

  ensure-every-endpoint-has-a-reference-group:
    description: Ensures every endpoint belongs to a reference category
    given: $.paths[*][*]
    severity: error
    recommended: true
    message: "{{error}}"
    then:
      field: 'x-box-reference-category'
      function: truthy

  ensure-every-resource-has-title:
    description: Ensures every resource has a title
    given: '$.components.schemas[*]'
    severity: error
    recommended: true
    message: "{{error}}"
    then:
      field: 'title'
      function: truthy