---
title: Workflow

type: object

x-box-resource-id: workflow
x-box-variant: standard

description: |-
  Box Relay Workflows are objects that represent a named collection of flows

allOf:
  - $ref: '#/components/schemas/Workflow--Mini'
  - properties:
      flows:
        type: array
        description: |-
          A list of flows assigned to a workflow.
        items:
          type: object
          description: |-
            A step in a Box Relay Workflow. Each flow contains a `Trigger` and
            a collection of Outcomes to perform once the conditions of a
            `Trigger` are met
          properties:
            id:
              type: string
              description: The identifier of the flow
              example: '12345'
            type:
              type: string
              description: The flow's resource type
              example: flow
              enum:
                - flow
            trigger:
              allOf:
                - $ref: '../attributes/trigger.yml'
                - description: Trigger that initiates flow
            outcomes:
              allOf:
                - $ref: '../attributes/outcomes.yml'
                - description: |-
                    Actions that are completed once the flow is triggered
            created_at:
              type: string
              format: date-time
              description: When this flow was created
              example: '2012-12-12T10:53:43-08:00'
            created_by:
              allOf:
                - $ref: '#/components/schemas/User--Base'
                - description: The user who created this flow
