blank_issues_enabled: false
contact_links:
  - name: Box Developer Community
    url: https://forum.box.com
    about: Before creating an issue, I have searched the Box Developer Community and my issue isn't already reported there.
  - name: Issues
    url: https://github.com/box/box-openapi/issues
    about: Before creating an issue, I have searched Issues in this repository and my issue isn't already reported there.
  - name: API Reference
    url: https://developer.box.com/reference
    about: Before creating an issue, I have checked that the API documentation doesn't solve my issue.