name: API documentation error
description: Report a typo or error found in API documentation
labels: ["documentation"]
body:
  - type: textarea
    attributes:
      label: Description of the issue
      description: Describe what you discovered and explain why it is an issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current content
      description: What does the specification currently say?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected content
      description: What should the specification say instead?
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: Link to the documentation page
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"